name: Locust Stress Test

on: 
  push:
      branches:
          - main
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2 AM UTC

jobs:
    stress-test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up a python
          uses: actions/setup-python@v5
          with:
            python-version: '3.13'

        - name: Install dependencies
          run: 
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Locust Stress Test
          run: |
            locust -f locustfile.py \
            -u 1000 -r 100 \
            -H http://jsonplaceholder.typicode.com \
            --csv=locust_report 

        - name: upload CSV report
          uses: actions/upload-artifact@v4
          with:
            name: locust-csv-report
            paths: |
              locust_report*.csv

